// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../../resource';
import * as ShipmentsAPI from './shipments/shipments';
import {
  Address1,
  Alert,
  Contact1,
  ContactAndAddress,
  CurrencyExchangeRate,
  CustomerImageUsage,
  CustomerReference,
  CustomsClearanceDetail,
  DeliveryOnInvoiceAcceptanceDetail,
  DocTabZoneSpecification,
  DocumentFormatOptionsRequested,
  EtdDetail,
  HoldAtLocationDetail,
  HomeDeliveryPremiumDetail,
  InternationalControlledExportDetail,
  InternationalTrafficInArmsRegulationsDetail,
  LabelResponseVo,
  LabelSpecification,
  Message,
  Money,
  Party1,
  Party3,
  PartyAccountNumber,
  PartyAddress,
  PartyAddress2,
  PartyContact,
  Payment,
  PendingShipmentDetail,
  RateDiscount,
  RecipientsParty,
  RequestedPackageLineItem,
  RequestedShipment,
  ReturnShipmentDetail,
  ShipmentCancelParams,
  ShipmentCancelResponse,
  ShipmentCodDetail,
  ShipmentCreateParams,
  ShipmentCreateResponse,
  ShipmentDryIceDetail1,
  ShipmentRetrieveAsyncParams,
  ShipmentRetrieveAsyncResponse,
  Shipments,
  ShipperAccountNumber,
  ShipperParty,
  ShippingDocumentDispositionDetail,
  ShippingDocumentFormat,
  ShippingDocumentSpecification,
  SmartPostInfoDetail,
  Surcharge,
  Tax,
  TaxpayerIdentification,
  TrackingID,
  TransactionShipmentOutputVo,
  UploadDocumentReferenceDetail,
  VariableHandlingChargeDetail,
  Weight,
} from './shipments/shipments';

export class V1 extends APIResource {
  shipments: ShipmentsAPI.Shipments = new ShipmentsAPI.Shipments(this._client);
}

V1.Shipments = Shipments;

export declare namespace V1 {
  export {
    Shipments as Shipments,
    type Address1 as Address1,
    type Alert as Alert,
    type Contact1 as Contact1,
    type ContactAndAddress as ContactAndAddress,
    type CurrencyExchangeRate as CurrencyExchangeRate,
    type CustomerImageUsage as CustomerImageUsage,
    type CustomerReference as CustomerReference,
    type CustomsClearanceDetail as CustomsClearanceDetail,
    type DeliveryOnInvoiceAcceptanceDetail as DeliveryOnInvoiceAcceptanceDetail,
    type DocTabZoneSpecification as DocTabZoneSpecification,
    type DocumentFormatOptionsRequested as DocumentFormatOptionsRequested,
    type EtdDetail as EtdDetail,
    type HoldAtLocationDetail as HoldAtLocationDetail,
    type HomeDeliveryPremiumDetail as HomeDeliveryPremiumDetail,
    type InternationalControlledExportDetail as InternationalControlledExportDetail,
    type InternationalTrafficInArmsRegulationsDetail as InternationalTrafficInArmsRegulationsDetail,
    type LabelResponseVo as LabelResponseVo,
    type LabelSpecification as LabelSpecification,
    type Message as Message,
    type Money as Money,
    type Party1 as Party1,
    type Party3 as Party3,
    type PartyAccountNumber as PartyAccountNumber,
    type PartyAddress as PartyAddress,
    type PartyAddress2 as PartyAddress2,
    type PartyContact as PartyContact,
    type Payment as Payment,
    type PendingShipmentDetail as PendingShipmentDetail,
    type RateDiscount as RateDiscount,
    type RecipientsParty as RecipientsParty,
    type RequestedPackageLineItem as RequestedPackageLineItem,
    type RequestedShipment as RequestedShipment,
    type ReturnShipmentDetail as ReturnShipmentDetail,
    type ShipmentCodDetail as ShipmentCodDetail,
    type ShipmentDryIceDetail1 as ShipmentDryIceDetail1,
    type ShipperAccountNumber as ShipperAccountNumber,
    type ShipperParty as ShipperParty,
    type ShippingDocumentDispositionDetail as ShippingDocumentDispositionDetail,
    type ShippingDocumentFormat as ShippingDocumentFormat,
    type ShippingDocumentSpecification as ShippingDocumentSpecification,
    type SmartPostInfoDetail as SmartPostInfoDetail,
    type Surcharge as Surcharge,
    type Tax as Tax,
    type TaxpayerIdentification as TaxpayerIdentification,
    type TrackingID as TrackingID,
    type TransactionShipmentOutputVo as TransactionShipmentOutputVo,
    type UploadDocumentReferenceDetail as UploadDocumentReferenceDetail,
    type VariableHandlingChargeDetail as VariableHandlingChargeDetail,
    type Weight as Weight,
    type ShipmentCreateResponse as ShipmentCreateResponse,
    type ShipmentCancelResponse as ShipmentCancelResponse,
    type ShipmentRetrieveAsyncResponse as ShipmentRetrieveAsyncResponse,
    type ShipmentCreateParams as ShipmentCreateParams,
    type ShipmentCancelParams as ShipmentCancelParams,
    type ShipmentRetrieveAsyncParams as ShipmentRetrieveAsyncParams,
  };
}
